model:
  stage2_path: artifacts/models/best.mlpackage
  device: coreml
stage1:
  use_sahi: true
  slice_size: 640
  overlap: 0.3
  imgsz: 1280
  postprocess_type: NMM
  match_threshold: 0.3
  detector_path: runs/stage1_det/yolov8s_stage1/weights/best.pt
input:
  frame_interval_ms: 250
  post_interval_s: 2.0
postprocess:
  smoothing_window: 5
  classifier_threshold: 0.3
logging:
  output_dir: logs
  format: json
rois:
  spot_1:
    - 641
    - 382
    - 698
    - 488
  spot_2:
    - 589
    - 380
    - 643
    - 488
  spot_3:
    - 535
    - 380
    - 588
    - 488
  spot_4:
    - 480
    - 381
    - 535
    - 487
  spot_5:
    - 430
    - 381
    - 479
    - 487
  spot_6:
    - 377
    - 382
    - 428
    - 489
  spot_7:
    - 325
    - 378
    - 376
    - 491
  spot_8:
    - 269
    - 380
    - 325
    - 488
  spot_9:
    - 218
    - 380
    - 269
    - 489
  spot_10:
    - 212
    - 487
    - 254
    - 601
  spot_11:
    - 264
    - 485
    - 312
    - 605
  spot_12:
    - 322
    - 487
    - 365
    - 601
  spot_13:
    - 372
    - 489
    - 426
    - 602
  spot_14:
    - 428
    - 491
    - 478
    - 601
  spot_15:
    - 482
    - 491
    - 535
    - 610
  spot_16:
    - 537
    - 495
    - 588
    - 608
  spot_17:
    - 590
    - 493
    - 645
    - 611
  spot_18:
    - 643
    - 491
    - 702
    - 607
  spot_19:
    - 702
    - 489
    - 758
    - 604
  spot_20:
    - 759
    - 491
    - 814
    - 606
  spot_21:
    - 814
    - 489
    - 871
    - 603
  spot_22:
    - 869
    - 490
    - 928
    - 605
  spot_23:
    - 927
    - 488
    - 985
    - 605
  spot_24:
    - 976
    - 490
    - 1036
    - 600
  spot_25:
    - 1023
    - 492
    - 1095
    - 599
  spot_26:
    - 154
    - 162
    - 197
    - 256
  spot_27:
    - 206
    - 162
    - 249
    - 256
  spot_28:
    - 254
    - 168
    - 296
    - 253
  spot_29:
    - 306
    - 165
    - 349
    - 255
  spot_30:
    - 356
    - 165
    - 396
    - 257
  spot_31:
    - 397
    - 159
    - 451
    - 265
  spot_32:
    - 453
    - 167
    - 499
    - 261
  spot_33:
    - 502
    - 167
    - 552
    - 260
  spot_34:
    - 551
    - 168
    - 603
    - 260
  spot_35:
    - 602
    - 168
    - 650
    - 262
  spot_36:
    - 649
    - 167
    - 703
    - 263
  spot_37:
    - 699
    - 170
    - 752
    - 259
  spot_38:
    - 752
    - 171
    - 803
    - 263
  spot_39:
    - 799
    - 168
    - 854
    - 263
  spot_40:
    - 849
    - 171
    - 905
    - 261
  spot_41:
    - 898
    - 171
    - 954
    - 260
  spot_42:
    - 947
    - 171
    - 1003
    - 260
  spot_43:
    - 999
    - 172
    - 1056
    - 260
  spot_44:
    - 1054
    - 173
    - 1096
    - 254
  spot_45:
    - 699
    - 383
    - 753
    - 473
  spot_46:
    - 749
    - 384
    - 808
    - 469
  spot_47:
    - 803
    - 386
    - 861
    - 468
  spot_48:
    - 855
    - 390
    - 910
    - 467
  spot_49:
    - 907
    - 391
    - 962
    - 468
  spot_50:
    - 961
    - 389
    - 1016
    - 468
  spot_51:
    - 1008
    - 389
    - 1070
    - 470
